### ISSUE TITLE
reuseSession is never read from web.xml

### ISSUE THREAD

**Issue by beat2** [wso2-extensions/identity-agent-entitlement-filter#6]
The instance variable "resuseSession" in EntitlementFilter is never initialized, but used (always null). The value should most possibly be read from the web.xml if configured.

Usecase: We need to set resuseSession to false, because otherwise we will get a session timeout after some time (SOAP).

**Comment by ruwanta** [comment]
We are not maintaining this repository any more and will be moved to https://github.com/wso2-attic
